<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2009-09-15 18:31

$extensionPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('solrgrouping');
return array(

	'ApacheSolrForTypo3\Solrgrouping\Classloader' => $extensionPath . 'Classes/Classloader.php',


	'ApacheSolrForTypo3\Solrgrouping\Query\Modifier\Grouping' => $extensionPath . 'Classes/Query/Modifier/Grouping.php',

	'ApacheSolrForTypo3\Solrgrouping\Response\Modifier\Grouping' => $extensionPath . 'Classes/Response/Modifier/Grouping.php',

	'ApacheSolrForTypo3\Solrgrouping\Search\GroupingComponent' => $extensionPath . 'Classes/Search/GroupingComponent.php',

);