<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2009-09-15 18:31

$extensionPath = t3lib_extMgm::extPath('solrgrouping');
return array(

	'tx_solrgrouping_classloader' => $extensionPath . 'classes/class.tx_solrgrouping_classloader.php',


	'tx_solr_query_modifier_grouping' => $extensionPath . 'classes/query/modifier/class.tx_solr_query_modifier_grouping.php',

	'tx_solr_response_modifier_grouping' => $extensionPath . 'classes/response/modifier/class.tx_solr_response_modifier_grouping.php',

	'tx_solr_search_groupingcomponent' => $extensionPath . 'classes/search/class.tx_solr_search_groupingcomponent.php',

);
?>